/**
 * Write shared env values into every apps/<brand>/.env at once, so you set the
 * single shared token in ONE place for local dev.
 *
 *   SHOPIFY_STORE_DOMAIN=arvoalux-platform-dev.myshopify.com \
 *   SHOPIFY_PRIVATE_TOKEN=shpat_xxx \
 *   node scripts/sync-env.mjs
 *
 * In production you still set these in each deployment's own env dashboard;
 * this is purely a local-dev convenience. Per-app overrides (a brand-specific
 * SHOPIFY_PRIVATE_TOKEN_<HANDLE>) are never touched.
 */
import { readdirSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";

const STORE = process.env.SHOPIFY_STORE_DOMAIN;
const TOKEN = process.env.SHOPIFY_PRIVATE_TOKEN;
const VERSION = process.env.SHOPIFY_API_VERSION ?? "2026-01";

if (!STORE || !TOKEN) {
  console.error("Set SHOPIFY_STORE_DOMAIN and SHOPIFY_PRIVATE_TOKEN.");
  process.exit(1);
}

const appsDir = join(process.cwd(), "apps");
const brands = readdirSync(appsDir).filter((d) => statSync(join(appsDir, d)).isDirectory());

const body =
  `# Generated by scripts/sync-env.mjs — shared dev values.\n` +
  `SHOPIFY_STORE_DOMAIN=${STORE}\n` +
  `SHOPIFY_API_VERSION=${VERSION}\n` +
  `SHOPIFY_PRIVATE_TOKEN=${TOKEN}\n`;

for (const b of brands) {
  const envPath = join(appsDir, b, ".env");
  writeFileSync(envPath, body);
  console.log(`${existsSync(envPath) ? "wrote" : "created"} apps/${b}/.env`);
}

console.log(`\nDone — ${brands.length} app(s) now share the same token.`);
